//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Notifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Notifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AboutBackGroundDialog {
            get {
                object obj = ResourceManager.GetObject("AboutBackGroundDialog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect User or Password.
        /// </summary>
        internal static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        internal static string AccessDeniedTitle {
            get {
                return ResourceManager.GetString("AccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApplicationLogo {
            get {
                object obj = ResourceManager.GetObject("ApplicationLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Notifier.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If problem persists please restart MySQL Notifier.
        /// </summary>
        internal static string AskRestartApplication {
            get {
                return ResourceManager.GetString("AskRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} failed the most recent status change request with the message {1}..
        /// </summary>
        internal static string BalloonTextFailedStatusChange {
            get {
                return ResourceManager.GetString("BalloonTextFailedStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MySQL instance {0} failed the most recent connection status check with the following error
        ///
        ///{1}.
        /// </summary>
        internal static string BalloonTextFailedStatusCheck {
            get {
                return ResourceManager.GetString("BalloonTextFailedStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Instance {0} changed status to {1}....
        /// </summary>
        internal static string BalloonTextInstanceStatus {
            get {
                return ResourceManager.GetString("BalloonTextInstanceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine {0} has been added to the monitoring list..
        /// </summary>
        internal static string BalloonTextMachineAdded {
            get {
                return ResourceManager.GetString("BalloonTextMachineAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine {0} has been removed from the monitoring list..
        /// </summary>
        internal static string BalloonTextMachineRemoved {
            get {
                return ResourceManager.GetString("BalloonTextMachineRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine {0} changed connection status to {1}....
        /// </summary>
        internal static string BalloonTextMachineStatus {
            get {
                return ResourceManager.GetString("BalloonTextMachineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New service added to monitored list: {0}.
        /// </summary>
        internal static string BalloonTextServiceList {
            get {
                return ResourceManager.GetString("BalloonTextServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} has been removed from the monitoring list.  .
        /// </summary>
        internal static string BalloonTextServiceRemoved {
            get {
                return ResourceManager.GetString("BalloonTextServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} changed status from {1} to {2}....
        /// </summary>
        internal static string BalloonTextServiceStatus {
            get {
                return ResourceManager.GetString("BalloonTextServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string BalloonTitleFailedStatusChange {
            get {
                return ResourceManager.GetString("BalloonTitleFailedStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Instance Status Changed.
        /// </summary>
        internal static string BalloonTitleInstanceStatus {
            get {
                return ResourceManager.GetString("BalloonTitleInstanceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines List Changed.
        /// </summary>
        internal static string BalloonTitleMachinesList {
            get {
                return ResourceManager.GetString("BalloonTitleMachinesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Status Changed.
        /// </summary>
        internal static string BalloonTitleMachineStatus {
            get {
                return ResourceManager.GetString("BalloonTitleMachineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services List Changed.
        /// </summary>
        internal static string BalloonTitleServiceList {
            get {
                return ResourceManager.GetString("BalloonTitleServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status Changed.
        /// </summary>
        internal static string BalloonTitleServiceStatus {
            get {
                return ResourceManager.GetString("BalloonTitleServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} was not found in the Windows Services.
        /// </summary>
        internal static string BaloonTextServiceNotFound {
            get {
                return ResourceManager.GetString("BaloonTextServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localhost or 127.0.0.1 are invalid host names for a remote computer..
        /// </summary>
        internal static string CannotAddLocalhostMessage {
            get {
                return ResourceManager.GetString("CannotAddLocalhostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host.
        /// </summary>
        internal static string CannotAddLocalhostTitle {
            get {
                return ResourceManager.GetString("CannotAddLocalhostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckForUpdatesIcon {
            get {
                object obj = ResourceManager.GetObject("CheckForUpdatesIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are checking for updates to your installed MySQLsoftware..
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates....
        /// </summary>
        internal static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Instance....
        /// </summary>
        internal static string ConfigureInstance {
            get {
                return ResourceManager.GetString("ConfigureInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a MySQL instance already being monitored that this connection relates to..
        /// </summary>
        internal static string ConnectionAlreadyInInstancesDetail {
            get {
                return ResourceManager.GetString("ConnectionAlreadyInInstancesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace the monitored MySQL instance&apos;s Workbench connection with this one?.
        /// </summary>
        internal static string ConnectionAlreadyInInstancesSubDetail {
            get {
                return ResourceManager.GetString("ConnectionAlreadyInInstancesSubDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL instance already exists.
        /// </summary>
        internal static string ConnectionAlreadyInInstancesTitle {
            get {
                return ResourceManager.GetString("ConnectionAlreadyInInstancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are able to monitor services in this remote machine..
        /// </summary>
        internal static string ConnectionSuccessfulMessage {
            get {
                return ResourceManager.GetString("ConnectionSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Successful.
        /// </summary>
        internal static string ConnectionSuccessfulTitle {
            get {
                return ResourceManager.GetString("ConnectionSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Pending.
        /// </summary>
        internal static string ContinuePending {
            get {
                return ResourceManager.GetString("ContinuePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected machine and all its monitored services?.
        /// </summary>
        internal static string DeleteMachineConfirmationText {
            get {
                return ResourceManager.GetString("DeleteMachineConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Machine.
        /// </summary>
        internal static string DeleteMachineConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteMachineConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Remote Machine.
        /// </summary>
        internal static string EditMachineText {
            get {
                return ResourceManager.GetString("EditMachineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbench failed to launch with the error: {0}.
        /// </summary>
        internal static string FailureToLaunchWorkbench {
            get {
                return ResourceManager.GetString("FailureToLaunchWorkbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are updates to your installed MySQL software.   Please launch the MySQL Installer to apply them..
        /// </summary>
        internal static string HasUpdatesLaunchInstaller {
            get {
                return ResourceManager.GetString("HasUpdatesLaunchInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Severity Error.
        /// </summary>
        internal static string HighSeverityError {
            get {
                return ResourceManager.GetString("HighSeverityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message can be displayed for one of the following reasons at the remote machine:
        ///   * Machine is offline
        ///   * WMI/DCOM access permissions are insufficient for user attempting to connect
        ///   * Windows Firewall is not configured for WMI communication.
        /// </summary>
        internal static string HostUnavailableExtendedMessage {
            get {
                return ResourceManager.GetString("HostUnavailableExtendedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host you selected is not available at this moment, it was not possible to establish a WMI connection..
        /// </summary>
        internal static string HostUnavailableMessage {
            get {
                return ResourceManager.GetString("HostUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Currently Unavailable.
        /// </summary>
        internal static string HostUnavailableTitle {
            get {
                return ResourceManager.GetString("HostUnavailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InstallAvailableUpdatesIcon {
            get {
                object obj = ResourceManager.GetObject("InstallAvailableUpdatesIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Installer For Windows 1.1 or later must be installed{0}to enable check for updates..
        /// </summary>
        internal static string Installer11RequiredForCheckForUpdates {
            get {
                return ResourceManager.GetString("Installer11RequiredForCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch MySQL Installer....
        /// </summary>
        internal static string LaunchInstaller {
            get {
                return ResourceManager.GetString("LaunchInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LaunchUtilities {
            get {
                object obj = ResourceManager.GetObject("LaunchUtilities", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_mysql {
            get {
                object obj = ResourceManager.GetObject("logo_mysql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine you&apos;re attempting to add already exists on the list of machines monitoring services..
        /// </summary>
        internal static string MachineAlreadyExistMessage {
            get {
                return ResourceManager.GetString("MachineAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine already exists.
        /// </summary>
        internal static string MachineAlreadyExistTitle {
            get {
                return ResourceManager.GetString("MachineAlreadyExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Service Instances....
        /// </summary>
        internal static string ManageServices {
            get {
                return ResourceManager.GetString("ManageServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ManageServicesIcon {
            get {
                object obj = ResourceManager.GetObject("ManageServicesIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing MySQL Installer.
        /// </summary>
        internal static string MissingMySQLInstaller {
            get {
                return ResourceManager.GetString("MissingMySQLInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Instances.
        /// </summary>
        internal static string MySQLInstances {
            get {
                return ResourceManager.GetString("MySQLInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MySqlNotifierIcon {
            get {
                object obj = ResourceManager.GetObject("MySqlNotifierIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem retrieving Windows Services.
        /// </summary>
        internal static string NoServicesExceptionMessage {
            get {
                return ResourceManager.GetString("NoServicesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierErrorImage {
            get {
                object obj = ResourceManager.GetObject("NotifierErrorImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIcon {
            get {
                object obj = ResourceManager.GetObject("NotifierIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconAlert {
            get {
                object obj = ResourceManager.GetObject("NotifierIconAlert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconRunning {
            get {
                object obj = ResourceManager.GetObject("NotifierIconRunning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconRunningAlert {
            get {
                object obj = ResourceManager.GetObject("NotifierIconRunningAlert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStarting {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStarting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStartingAlert {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStartingAlert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStartingAlertStrong {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStartingAlertStrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStartingStrong {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStartingStrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStopped {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStopped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStoppedAlert {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStoppedAlert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStoppedAlertStrong {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStoppedAlertStrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierIconStoppedStrong {
            get {
                object obj = ResourceManager.GetObject("NotifierIconStoppedStrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierWarningImage {
            get {
                object obj = ResourceManager.GetObject("NotifierWarningImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates did not find any new version.
        /// </summary>
        internal static string NoUpdatesFound {
            get {
                return ResourceManager.GetString("NoUpdatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Pending.
        /// </summary>
        internal static string PausePending {
            get {
                return ResourceManager.GetString("PausePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string RefreshMethodHard {
            get {
                return ResourceManager.GetString("RefreshMethodHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        internal static string RefreshMethodSoft {
            get {
                return ResourceManager.GetString("RefreshMethodSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Service Instances.
        /// </summary>
        internal static string RefreshServices {
            get {
                return ResourceManager.GetString("RefreshServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheduled update check requires that MySQL Installer for Windows 1.1 or later be installed..
        /// </summary>
        internal static string ScheduledCheckRequiresInstaller11 {
            get {
                return ResourceManager.GetString("ScheduledCheckRequiresInstaller11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected service is already in the list of monitored services..
        /// </summary>
        internal static string ServiceAlreadyInListWarningText {
            get {
                return ResourceManager.GetString("ServiceAlreadyInListWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading application settings failed.  The application will continue to run but may not behave as you would expect..
        /// </summary>
        internal static string SettingsFileFailedToLoad {
            get {
                return ResourceManager.GetString("SettingsFileFailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        internal static string SoftwareUpdate {
            get {
                return ResourceManager.GetString("SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Editor....
        /// </summary>
        internal static string SQLEditor {
            get {
                return ResourceManager.GetString("SQLEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StartInstallerIcon {
            get {
                object obj = ResourceManager.GetObject("StartInstallerIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pending.
        /// </summary>
        internal static string StartPending {
            get {
                return ResourceManager.GetString("StartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Pending.
        /// </summary>
        internal static string StopPending {
            get {
                return ResourceManager.GetString("StopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring {0} services and {1} instances.
        /// </summary>
        internal static string ToolTipText {
            get {
                return ResourceManager.GetString("ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported XML File Version.
        /// </summary>
        internal static string UnSupportedWBXMLVersion {
            get {
                return ResourceManager.GetString("UnSupportedWBXMLVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
