//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.TrayApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.TrayApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon app_default {
            get {
                object obj = ResourceManager.GetObject("app_default", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL TrayApp.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services list changed. {0} removed services / {1} added services....
        /// </summary>
        internal static string BalloonTextServiceList {
            get {
                return ResourceManager.GetString("BalloonTextServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} changed status from {1} to {2}....
        /// </summary>
        internal static string BalloonTextServiceStatus {
            get {
                return ResourceManager.GetString("BalloonTextServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services List Changed.
        /// </summary>
        internal static string BalloonTitleTextServiceList {
            get {
                return ResourceManager.GetString("BalloonTitleTextServiceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status Changed.
        /// </summary>
        internal static string BalloonTitleTextServiceStatus {
            get {
                return ResourceManager.GetString("BalloonTitleTextServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates....
        /// </summary>
        internal static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Instance....
        /// </summary>
        internal static string ConfigureInstance {
            get {
                return ResourceManager.GetString("ConfigureInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Pending.
        /// </summary>
        internal static string ContinuePending {
            get {
                return ResourceManager.GetString("ContinuePending", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap default_icon {
            get {
                object obj = ResourceManager.GetObject("default_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap iconDB {
            get {
                object obj = ResourceManager.GetObject("iconDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch MySQL Installer....
        /// </summary>
        internal static string LaunchInstaller {
            get {
                return ResourceManager.GetString("LaunchInstaller", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo_mysql {
            get {
                object obj = ResourceManager.GetObject("logo_mysql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Service Instances....
        /// </summary>
        internal static string ManageServices {
            get {
                return ResourceManager.GetString("ManageServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem retrieving Windows Services.
        /// </summary>
        internal static string NoServicesExceptionMessage {
            get {
                return ResourceManager.GetString("NoServicesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Pending.
        /// </summary>
        internal static string PausePending {
            get {
                return ResourceManager.GetString("PausePending", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string RefreshMethodHard {
            get {
                return ResourceManager.GetString("RefreshMethodHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft.
        /// </summary>
        internal static string RefreshMethodSoft {
            get {
                return ResourceManager.GetString("RefreshMethodSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Service Instances.
        /// </summary>
        internal static string RefreshServices {
            get {
                return ResourceManager.GetString("RefreshServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap running_icon {
            get {
                object obj = ResourceManager.GetObject("running_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Editor....
        /// </summary>
        internal static string SQLEditor {
            get {
                return ResourceManager.GetString("SQLEditor", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap starting_icon {
            get {
                object obj = ResourceManager.GetObject("starting_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pending.
        /// </summary>
        internal static string StartPending {
            get {
                return ResourceManager.GetString("StartPending", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap stopped_icon {
            get {
                object obj = ResourceManager.GetObject("stopped_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Pending.
        /// </summary>
        internal static string StopPending {
            get {
                return ResourceManager.GetString("StopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring {0} instances.
        /// </summary>
        internal static string ToolTipText {
            get {
                return ResourceManager.GetString("ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported XML File Version.
        /// </summary>
        internal static string UnSupportedWBXMLVersion {
            get {
                return ResourceManager.GetString("UnSupportedWBXMLVersion", resourceCulture);
            }
        }
    }
}
